using 'main.bicep'

param location = 'swedencentral'
param storageAccountName = 'diranyaistorage'
param keyVaultName = 'diranyai-kv-dev'
param containerAppsEnvironmentName = 'diranyai-env-dev'
param logAnalyticsWorkspaceName = 'workspacergdiranyaideva05c'
param backendName = 'diranyai-api'
param containerRegistryServer = 'diranyaicr.azurecr.io'
param applicationInsightsName = 'diranyai-appinsights-dev'
param backendImage = 'diranyaicr.azurecr.io/diranyai-api:latest'