// <auto-generated />
using System;
using DiranyAI.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DiranyAI.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260919220331_EnhanceStyleCatalog")]
    partial class EnhanceStyleCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DiranyAI.Api.Consultations.BeardCandidate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BeardStyleId")
                        .HasColumnType("bigint");

                    b.Property<long>("ConsultationId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("BeardStyleId");

                    b.HasIndex("ConsultationId", "BeardStyleId")
                        .IsUnique();

                    b.ToTable("BeardCandidates");
                });

            modelBuilder.Entity("DiranyAI.Api.Consultations.Consultation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Consultations");
                });

            modelBuilder.Entity("DiranyAI.Api.Consultations.ConsultationImage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("BeardCandidateId")
                        .HasColumnType("bigint");

                    b.Property<long>("ConsultationId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("HairCandidateId")
                        .HasColumnType("bigint");

                    b.Property<string>("ImageAngle")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ImageType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("BeardCandidateId");

                    b.HasIndex("ConsultationId");

                    b.HasIndex("HairCandidateId");

                    b.ToTable("ConsultationImages");
                });

            modelBuilder.Entity("DiranyAI.Api.Consultations.HairCandidate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ConsultationId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("HairStyleId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("HairStyleId");

                    b.HasIndex("ConsultationId", "HairStyleId")
                        .IsUnique();

                    b.ToTable("HairCandidates");
                });

            modelBuilder.Entity("DiranyAI.Api.Customers.Customer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("DiranyAI.Api.Styles.BeardStyle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AiPromptHint")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("BeardStyles");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AiPromptHint = "a short boxed beard with an even short length, a clean structured shape, defined cheek edges, and a crisp neckline",
                            Description = "A neatly trimmed short beard with a defined boxed shape and clean edges.",
                            IsActive = true,
                            Name = "Short Boxed Beard"
                        },
                        new
                        {
                            Id = 2L,
                            AiPromptHint = "a well-groomed fuller beard with natural volume that gradually tapers from the cheeks and jaw toward a longer, clearly defined point at the chin",
                            Description = "A fuller shaped beard that gradually narrows toward a defined point at the chin.",
                            IsActive = true,
                            Name = "Pointy Beard"
                        },
                        new
                        {
                            Id = 3L,
                            AiPromptHint = "a professionally barbered beard with a zero skin fade starting high on the cheeks and sideburns, gradually and seamlessly blending from almost bare skin into a dense fuller beard along the lower jaw and chin. No sharp or drawn cheek line; the cheek area should naturally fade into thicker facial hair toward the jaw. Keep the moustache completely disconnected from the beard with a clearly visible clean gap at both corners of the mouth. The moustache should be full, dark, neatly shaped and defined. Keep the lower beard full, dense and boxed with a crisp straight lower outline and a slightly fuller chin area. Keep the beard relatively short and sculpted, not long, pointed, rounded or bushy",
                            Description = "A faded boxed beard with near-bare cheeks, increasing density toward the jaw and chin, and a disconnected moustache.",
                            IsActive = true,
                            Name = "Italian Beard"
                        },
                        new
                        {
                            Id = 4L,
                            AiPromptHint = "short even designer stubble across the beard area with consistent very short length, natural density, and a clean well-groomed finish",
                            Description = "Very short facial hair maintained at an even length for a clean natural look.",
                            IsActive = true,
                            Name = "Stubble"
                        },
                        new
                        {
                            Id = 5L,
                            AiPromptHint = "a noticeably longer full beard with dense facial hair covering the cheeks, jawline and chin, substantial natural length and volume below the jaw, a fuller chin area, and a well-groomed balanced shape with clean edges. Keep it full and substantial rather than short or closely trimmed",
                            Description = "A longer, full and dense beard with natural volume across the cheeks, jawline, and chin.",
                            IsActive = true,
                            Name = "Full Beard"
                        });
                });

            modelBuilder.Entity("DiranyAI.Api.Styles.HairStyle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AiPromptHint")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("HairStyles");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AiPromptHint = "taper fade haircut with a clean gradual transition around the temples and neckline",
                            Description = "A gradual fade around the sideburns and neckline while keeping more length around the sides and top.",
                            IsActive = true,
                            Name = "Taper Fade"
                        },
                        new
                        {
                            Id = 2L,
                            AiPromptHint = "a very short buzz cut with an even cropped top, a clean sharp natural lineup around the forehead and temples, and a skin fade on the sides and back blending smoothly into the short top",
                            Description = "A very short buzz cut with a sharp lineup and a clean skin fade on the sides and back.",
                            IsActive = true,
                            Name = "Buzz Cut"
                        },
                        new
                        {
                            Id = 3L,
                            AiPromptHint = "modern mohawk with short sides and a defined longer strip through the center",
                            Description = "Shorter sides with a distinct longer strip of hair through the center.",
                            IsActive = true,
                            Name = "Mohawk"
                        },
                        new
                        {
                            Id = 4L,
                            AiPromptHint = "textured crop haircut with short sides and natural textured hair on top",
                            Description = "Short sides with a textured top styled naturally forward.",
                            IsActive = true,
                            Name = "Textured Crop"
                        },
                        new
                        {
                            Id = 5L,
                            AiPromptHint = "slicked-back hairstyle with longer hair on top styled naturally backward",
                            Description = "Longer hair on top styled backward for a clean structured look.",
                            IsActive = true,
                            Name = "Slick Back"
                        },
                        new
                        {
                            Id = 6L,
                            AiPromptHint = "classic side-part haircut with a clean defined natural side part, neatly combed top with moderate length and volume, and clean tapered shorter sides",
                            Description = "A clean classic haircut with a defined side part, neatly styled top, and tapered sides.",
                            IsActive = true,
                            Name = "Classic Side Part"
                        },
                        new
                        {
                            Id = 7L,
                            AiPromptHint = "modern quiff with medium-length hair on top, noticeable natural volume at the front styled upward and slightly backward, with shorter clean sides",
                            Description = "A voluminous hairstyle with the front lifted upward and backward while keeping the sides shorter.",
                            IsActive = true,
                            Name = "Quiff"
                        },
                        new
                        {
                            Id = 8L,
                            AiPromptHint = "modern textured mullet with shorter clean sides, textured medium-length hair on top, and visibly longer layered hair extending at the back",
                            Description = "A modern mullet with shorter sides, textured hair on top, and clearly longer hair at the back.",
                            IsActive = true,
                            Name = "Mullet"
                        });
                });

            modelBuilder.Entity("DiranyAI.Api.Consultations.BeardCandidate", b =>
                {
                    b.HasOne("DiranyAI.Api.Styles.BeardStyle", "BeardStyle")
                        .WithMany("BeardCandidates")
                        .HasForeignKey("BeardStyleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiranyAI.Api.Consultations.Consultation", "Consultation")
                        .WithMany("BeardCandidates")
                        .HasForeignKey("ConsultationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BeardStyle");

                    b.Navigation("Consultation");
                });

            modelBuilder.Entity("DiranyAI.Api.Consultations.Consultation", b =>
                {
                    b.HasOne("DiranyAI.Api.Customers.Customer", "Customer")
                        .WithMany("Consultations")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("DiranyAI.Api.Consultations.ConsultationImage", b =>
                {
                    b.HasOne("DiranyAI.Api.Consultations.BeardCandidate", "BeardCandidate")
                        .WithMany()
                        .HasForeignKey("BeardCandidateId");

                    b.HasOne("DiranyAI.Api.Consultations.Consultation", "Consultation")
                        .WithMany("Images")
                        .HasForeignKey("ConsultationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiranyAI.Api.Consultations.HairCandidate", "HairCandidate")
                        .WithMany()
                        .HasForeignKey("HairCandidateId");

                    b.Navigation("BeardCandidate");

                    b.Navigation("Consultation");

                    b.Navigation("HairCandidate");
                });

            modelBuilder.Entity("DiranyAI.Api.Consultations.HairCandidate", b =>
                {
                    b.HasOne("DiranyAI.Api.Consultations.Consultation", "Consultation")
                        .WithMany("HairCandidates")
                        .HasForeignKey("ConsultationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiranyAI.Api.Styles.HairStyle", "HairStyle")
                        .WithMany("HairCandidates")
                        .HasForeignKey("HairStyleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consultation");

                    b.Navigation("HairStyle");
                });

            modelBuilder.Entity("DiranyAI.Api.Consultations.Consultation", b =>
                {
                    b.Navigation("BeardCandidates");

                    b.Navigation("HairCandidates");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("DiranyAI.Api.Customers.Customer", b =>
                {
                    b.Navigation("Consultations");
                });

            modelBuilder.Entity("DiranyAI.Api.Styles.BeardStyle", b =>
                {
                    b.Navigation("BeardCandidates");
                });

            modelBuilder.Entity("DiranyAI.Api.Styles.HairStyle", b =>
                {
                    b.Navigation("HairCandidates");
                });
#pragma warning restore 612, 618
        }
    }
}
