// <auto-generated />
using System;
using DiranyAI.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DiranyAI.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260906233405_AddHairAndBeardCandidates")]
    partial class AddHairAndBeardCandidates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DiranyAI.Api.Consultations.BeardCandidate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BeardStyleId")
                        .HasColumnType("bigint");

                    b.Property<long>("ConsultationId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("BeardStyleId");

                    b.HasIndex("ConsultationId", "BeardStyleId")
                        .IsUnique();

                    b.ToTable("BeardCandidates");
                });

            modelBuilder.Entity("DiranyAI.Api.Consultations.Consultation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Consultations");
                });

            modelBuilder.Entity("DiranyAI.Api.Consultations.ConsultationImage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ConsultationId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ConsultationId");

                    b.ToTable("ConsultationImages");
                });

            modelBuilder.Entity("DiranyAI.Api.Consultations.HairCandidate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ConsultationId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("HairStyleId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("HairStyleId");

                    b.HasIndex("ConsultationId", "HairStyleId")
                        .IsUnique();

                    b.ToTable("HairCandidates");
                });

            modelBuilder.Entity("DiranyAI.Api.Customers.Customer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("DiranyAI.Api.Styles.BeardStyle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AiPromptHint")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("BeardStyles");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AiPromptHint = "short boxed beard with clean defined cheek lines, neckline, and even length",
                            Description = "A neatly trimmed short beard with defined cheek and neckline edges.",
                            IsActive = true,
                            Name = "Short Boxed Beard"
                        },
                        new
                        {
                            Id = 2L,
                            AiPromptHint = "well-groomed pointy beard tapering toward a defined point at the chin",
                            Description = "A shaped beard that gradually narrows toward a defined point at the chin.",
                            IsActive = true,
                            Name = "Pointy Beard"
                        },
                        new
                        {
                            Id = 3L,
                            AiPromptHint = "Italian-style full beard with a structured shape, clean cheek lines, and well-groomed finish",
                            Description = "A full, well-groomed beard with a defined shape and clean contours.",
                            IsActive = true,
                            Name = "Italian Beard"
                        },
                        new
                        {
                            Id = 4L,
                            AiPromptHint = "short even designer stubble with clean cheek and neckline edges",
                            Description = "Very short facial hair maintained at an even length for a natural rugged look.",
                            IsActive = true,
                            Name = "Stubble"
                        },
                        new
                        {
                            Id = 5L,
                            AiPromptHint = "full natural beard with balanced volume, groomed shape, and clean edges",
                            Description = "A full beard with natural volume covering the cheeks, jawline, and chin.",
                            IsActive = true,
                            Name = "Full Beard"
                        });
                });

            modelBuilder.Entity("DiranyAI.Api.Styles.HairStyle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AiPromptHint")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("HairStyles");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AiPromptHint = "taper fade haircut with a clean gradual transition around the temples and neckline",
                            Description = "A gradual fade around the sideburns and neckline while keeping more length around the sides and top.",
                            IsActive = true,
                            Name = "Taper Fade"
                        },
                        new
                        {
                            Id = 2L,
                            AiPromptHint = "short buzz cut with even length and a clean natural hairline",
                            Description = "A very short, even haircut with a clean and simple finish.",
                            IsActive = true,
                            Name = "Buzz Cut"
                        },
                        new
                        {
                            Id = 3L,
                            AiPromptHint = "modern mohawk with short sides and a defined longer strip through the center",
                            Description = "Shorter sides with a distinct longer strip of hair through the center.",
                            IsActive = true,
                            Name = "Mohawk"
                        },
                        new
                        {
                            Id = 4L,
                            AiPromptHint = "textured crop haircut with short sides and natural textured hair on top",
                            Description = "Short sides with a textured top styled naturally forward.",
                            IsActive = true,
                            Name = "Textured Crop"
                        },
                        new
                        {
                            Id = 5L,
                            AiPromptHint = "slicked-back hairstyle with longer hair on top styled naturally backward",
                            Description = "Longer hair on top styled backward for a clean structured look.",
                            IsActive = true,
                            Name = "Slick Back"
                        });
                });

            modelBuilder.Entity("DiranyAI.Api.Consultations.BeardCandidate", b =>
                {
                    b.HasOne("DiranyAI.Api.Styles.BeardStyle", "BeardStyle")
                        .WithMany("BeardCandidates")
                        .HasForeignKey("BeardStyleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiranyAI.Api.Consultations.Consultation", "Consultation")
                        .WithMany("BeardCandidates")
                        .HasForeignKey("ConsultationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BeardStyle");

                    b.Navigation("Consultation");
                });

            modelBuilder.Entity("DiranyAI.Api.Consultations.Consultation", b =>
                {
                    b.HasOne("DiranyAI.Api.Customers.Customer", "Customer")
                        .WithMany("Consultations")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("DiranyAI.Api.Consultations.ConsultationImage", b =>
                {
                    b.HasOne("DiranyAI.Api.Consultations.Consultation", "Consultation")
                        .WithMany("Images")
                        .HasForeignKey("ConsultationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consultation");
                });

            modelBuilder.Entity("DiranyAI.Api.Consultations.HairCandidate", b =>
                {
                    b.HasOne("DiranyAI.Api.Consultations.Consultation", "Consultation")
                        .WithMany("HairCandidates")
                        .HasForeignKey("ConsultationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiranyAI.Api.Styles.HairStyle", "HairStyle")
                        .WithMany("HairCandidates")
                        .HasForeignKey("HairStyleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consultation");

                    b.Navigation("HairStyle");
                });

            modelBuilder.Entity("DiranyAI.Api.Consultations.Consultation", b =>
                {
                    b.Navigation("BeardCandidates");

                    b.Navigation("HairCandidates");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("DiranyAI.Api.Customers.Customer", b =>
                {
                    b.Navigation("Consultations");
                });

            modelBuilder.Entity("DiranyAI.Api.Styles.BeardStyle", b =>
                {
                    b.Navigation("BeardCandidates");
                });

            modelBuilder.Entity("DiranyAI.Api.Styles.HairStyle", b =>
                {
                    b.Navigation("HairCandidates");
                });
#pragma warning restore 612, 618
        }
    }
}
